### PR TITLE
added what cells instructors need to have at the end of the notebook …

### PR DESCRIPTION
**Pull request by buedaswag**
adds instructions on what instructors need to include in the Exercise Notebook so that it has grading

### CODE REVIEW

**Comment by mariana-s-fernandes** [comment]
Hi, can you be more explicit in which directory should the `pip freeze` be executed? Thanks!

**Comment by mariana-s-fernandes** [comment]
There is a typo both in the screenshot and the cell code bellow it. It has "sumit" instead of "submit"

**Comment by mariana-s-fernandes** [comment]
Typo here too:

> This serves to collect the student slack ids so that we know hwo has submitted the LU.

**Comment by mariana-s-fernandes** [comment]
One more for the spam: the sections from `use with curl` and below, what is their purpose? If they are not relevant for the instructor to use, could we make them a separate section and be clear on what is that for?

Thank you!

**Comment by InesPessoa** [comment]
Can we already replace the pip install requests with pip install -r requirments.txt ? We can use this one https://github.com/LDSSA/nb-grades-collector/blob/submit_with_grading/instructores_example/requirements.txt

**Comment by InesPessoa** [comment]
I also agree with Mariana regarding the curl and heroku part in this readme. It might be a good idea to separate the readme into two parts, one readme for the instructors who will need to include the grading system in their SLUs, and another readme for who will be maintaining the API.

**Comment by InesPessoa** [comment]
On the autograded answer, don't we need to put something like this after slack_id=None, so it runs on circleci, or that is not necessary?

/### BEGIN SOLUTION
/slack_id = "ADMNSLU00"
/### END SOLUTION


Note: Ignore the '/'. It is just here because I was fighting with the markdown :) .

**Comment by buedaswag** [comment]
> On the autograded answer, don't we need to put something like this after slack_id=None, so it runs on circleci, or that is not necessary?
> 
> /### BEGIN SOLUTION
> /slack_id = "ADMNSLU00"
> /### END SOLUTION
> 
> Note: Ignore the '/'. It is just here because I was fighting with the markdown :) .

good question,
not necessary!

**Comment by buedaswag** [comment]
i agree with all of the suggestion, thank you @InesPessoa and @mariana-s-fernandes !

what do you think now?

**Review by mariana-s-fernandes — APPROVED** [review]
Looks fine by me! Thanks!

**Pull request merged**
